### ISSUE TITLE
Org switch doesn't work when grafana is accessible via URL sub-path

### ISSUE THREAD

**Issue by dpotapov** [digiapulssi/grafana-organisations-panel#14]
For example, Grafana is accessible by http://localhost/grafana/.

If we select the Main Org., the URL in the browser will look like: http://localhost/grafana/?orgId=1

In that case org switch buttons are producing wrong URLs: http://localhost/grafana/?orgId=1/?orgId=2

Notice repeasting `/?orgId=`

**Comment by timyllym** [comment]
Are you using the Organisations panel in some dashboard? In that case the url should have the dashboard id and name e.g. https://play.grafana.org/d/000000012/grafana-play-home?orgId=1

Organisation panel needs to know the base url for Grafana in order to navigate forward. Now it assumes that org panel is inside dashboard and url contains /d/ and takes the base url by split("/d/")[0]. 

But now your url doesn't seem to contain /d/ so it fails. Are you using reverse proxy to hide /d/ from url?

**Comment by dpotapov** [comment]
Oh that make sense. I have the panel on a home dashboard, so there is no `/d/` in the URL. Would it possible to allow it working in that scenario?

**Comment by timyllym** [comment]
I made a change so it should work now. It will take a while for the Grafana plugin repository to accept the update though.
